const eras=[
 {year:'1920',title:'The Broadcast Age',tag:'HEAR THE WORLD',text:'Radio transformed information from something you read into something you could hear together. Mass communication became immediate and shared.',shift:'Information moved from page → airwaves.',objects:['Radio','Broadcasting','Public information'],fact:'Radio became a defining mass medium of the 20th century.'},
 {year:'1950',title:'The Machine Age',tag:'ELECTRONICS ENTER HOME',text:'Television entered living rooms while early computers occupied entire rooms. Electronics started becoming part of ordinary life.',shift:'Entertainment and computation became electronic.',objects:['Television','Transistor','Mainframe'],fact:'Transistors helped make smaller, more practical electronics possible.'},
 {year:'1980',title:'The Personal Age',tag:'TECH BECOMES YOURS',text:'The computer left the laboratory. Personal machines, home consoles and portable music turned technology into something you owned.',shift:'Computing moved from institutions → individuals.',objects:['IBM PC','Walkman','Home console'],fact:'The IBM PC 5150 launched in 1981 and helped define the modern PC category.'},
 {year:'2000',title:'The Connected Age',tag:'DISTANCE DISAPPEARS',text:'The web changed the idea of distance. Search, email, digital music and online communities moved everyday activity onto screens.',shift:'Information moved from local → networked.',objects:['Web','Search','Mobile'],fact:'The World Wide Web was created at CERN and opened to the public in 1993.'},
 {year:'2020',title:'The Intelligent Age',tag:'COMPUTATION EVERYWHERE',text:'Cloud computing, smartphones, machine learning and remote collaboration blurred the line between physical and digital life.',shift:'Software moved from tool → environment.',objects:['AI','Cloud','Smartphone'],fact:'Generative AI made machine-produced language, images and code widely accessible.'},
 {year:'2035',title:'The Designed Future',tag:'YOU CHOOSE THE DIRECTION',text:'A speculative era. Instead of predicting one future, choose the technologies you believe will shape yours.',shift:'The question changes from “what happens?” → “what do we choose?”',objects:['AI','Robotics','AR'],fact:'This era is intentionally speculative — it is a design exercise, not a forecast.'}
];
const artifacts=[
 {icon:'◉',year:'1979',name:'Sony Walkman TPS-L2',era:'1980',image:'assets/walkman.svg',desc:'A portable cassette player that helped redefine personal listening. Music no longer needed to stay in one room.',meta:'Portable audio · cassette',source:'Wikimedia Commons category: Walkman'},
 {icon:'⌨',year:'1981',name:'IBM Personal Computer 5150',era:'1980',image:'assets/ibm.svg',desc:'IBM’s 5150 helped establish a widely copied personal-computer standard and brought serious computing into offices and homes.',meta:'Personal computing · MS-DOS',source:'Wikimedia Commons · CC BY-SA / GFDL'},
 {icon:'⌁',year:'1989',name:'World Wide Web',era:'2000',image:'assets/web.svg',desc:'Tim Berners-Lee proposed the World Wide Web at CERN in 1989. The system connected documents through hypertext and URLs.',meta:'Web · CERN · hypertext',source:'Wikimedia Commons / World Wide Web'},
 {icon:'▣',year:'2007',name:'First iPhone era',era:'2000',image:'assets/iphone.svg',desc:'The smartphone increasingly became a single interface for communication, photography, maps, media and the web.',meta:'Mobile computing · touch',source:'Wikimedia Commons · CC BY 2.0'},
 {icon:'✦',year:'2012',name:'Deep Learning Breakthrough',era:'2020',image:'',desc:'Neural-network methods became dramatically more capable on large datasets and powerful GPUs, accelerating computer vision and speech systems.',meta:'Machine learning · neural networks',source:'Concept record · no image required'},
 {icon:'✺',year:'2024',name:'Generative AI',era:'2020',image:'',desc:'Generative systems made it practical for ordinary users to request language, images, code and other media from a conversational interface.',meta:'AI · generation · interfaces',source:'Concept record · no image required'}
];
const nav=document.getElementById('eraNav'),card=document.getElementById('eraCard'),dialYear=document.getElementById('dialYear');let eraIndex=0;
function showEra(i){eraIndex=(i+eras.length)%eras.length;const e=eras[eraIndex];nav.innerHTML=eras.map((x,n)=>`<button class="era-btn ${n===eraIndex?'active':''}" onclick="showEra(${n})"><span>${String(n+1).padStart(2,'0')}</span><b>${x.year}</b><small>${x.tag}</small></button>`).join('');card.innerHTML=`<div class="era-no">0${eraIndex+1} / 06</div><span class="year">ERA ${e.year}</span><div class="era-tag">${e.tag}</div><h3>${e.title}</h3><p>${e.text}</p><div class="shift"><span>THE SHIFT</span><b>${e.shift}</b></div><div class="era-objects">${e.objects.map(o=>`<span>${o}</span>`).join('')}</div><div class="era-fact"><span>ARCHIVE NOTE</span><b>${e.fact}</b></div>`;dialYear.textContent=e.year;document.querySelectorAll('.era-btn').forEach((b,n)=>b.classList.toggle('active',n===eraIndex));document.querySelector('.dial-marker').textContent=String(eraIndex+1).padStart(2,'0')}
showEra(0);
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')showEra(eraIndex+1);if(e.key==='ArrowLeft')showEra(eraIndex-1);if(e.key==='Escape')closeModal()});
const filters=document.getElementById('filters');let activeFilter='ALL';const erasFilter=['ALL','1979–1989','2000s','2020s'];filters.innerHTML=erasFilter.map(f=>`<button class="filter ${f==='ALL'?'active':''}" onclick="setFilter('${f}')">${f}</button>`).join('');
function setFilter(f){activeFilter=f;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.textContent===f));renderArtifacts()}
function renderArtifacts(){const q=document.getElementById('search').value.toLowerCase();const list=artifacts.filter(a=>{const eraOk=activeFilter==='ALL'||(activeFilter==='1979–1989'&&['1979','1981','1989'].includes(a.year))||(activeFilter==='2000s'&&a.era==='2000')||(activeFilter==='2020s'&&a.era==='2020');return eraOk&&(a.name.toLowerCase().includes(q)||a.desc.toLowerCase().includes(q)||a.meta.toLowerCase().includes(q))});document.getElementById('artifactGrid').innerHTML=list.map(a=>`<article class="artifact" onclick="openArtifact('${a.name.replaceAll("'","\\'")}')">${a.image?`<div class="artifact-img"><img src="${a.image}" alt="${a.name}" loading="lazy" onerror="this.onerror=null;this.src='assets/artifact-fallback.svg'"><span>${a.year}</span></div>`:`<div class="artifact-img placeholder"><span class="big-icon">${a.icon}</span><span>${a.year}</span></div>`}<div class="artifact-copy"><small>${a.meta}</small><h3>${a.name}</h3><p>${a.desc}</p></div><div class="artifact-foot"><small>OPEN RECORD →</small><span>${a.era}</span></div></article>`).join('');document.getElementById('resultCount').textContent=`${list.length} RECORD${list.length===1?'':'S'} SHOWN`}
document.getElementById('search').addEventListener('input',renderArtifacts);renderArtifacts();
function openArtifact(name){const a=artifacts.find(x=>x.name===name);document.getElementById('modalContent').innerHTML=`${a.image?`<img class="modal-image" src="${a.image}" alt="${a.name}" onerror="this.onerror=null;this.src='assets/artifact-fallback.svg'">`:''}<small>${a.year} / ARCHIVE RECORD</small><h2>${a.name}</h2><p>${a.desc}</p><div class="modal-meta"><span>${a.meta}</span><span>${a.source}</span></div>`;document.getElementById('modal').classList.add('open');document.getElementById('modal').setAttribute('aria-hidden','false')}
function closeModal(){document.getElementById('modal').classList.remove('open');document.getElementById('modal').setAttribute('aria-hidden','true')}
document.getElementById('closeModal').onclick=closeModal;document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
const slider=document.getElementById('compareSlider'),comparison=document.getElementById('comparison'),percent=document.getElementById('comparePercent');function updateCompare(){const v=slider.value;comparison.style.setProperty('--split',v+'%');percent.textContent=`${v} / ${100-v}`};slider.addEventListener('input',updateCompare);updateCompare();
const tech=[['AI','Artificial intelligence'],['ROB','Personal robotics'],['AR','Augmented reality'],['BIO','Biotechnology'],['QUA','Quantum computing'],['ENE','Clean energy']];const choices=document.getElementById('choices');let selected=[];choices.innerHTML=tech.map((t,i)=>`<button class="choice" onclick="pick(${i})"><b>${t[0]}</b><span>${t[1]}</span></button>`).join('');const futures={AI:'AI becomes an invisible co-pilot across education, work and everyday decisions.',ROB:'Personal robots handle physical tasks and become ordinary household tools.',AR:'Digital information sits naturally on top of the physical world.',BIO:'Personalized biology changes how people prevent and treat disease.',QUA:'Quantum systems tackle specialized problems beyond conventional machines.',ENE:'Cleaner energy reshapes transport, buildings and industry.'};
function pick(i){const key=tech[i][0];if(selected.includes(key))selected=selected.filter(x=>x!==key);else if(selected.length<3)selected.push(key);document.querySelectorAll('.choice').forEach((b,n)=>b.classList.toggle('selected',selected.includes(tech[n][0])));const out=document.getElementById('futureOutput');if(selected.length<3){out.innerHTML=`<span>SCENARIO // WAITING</span><b>Select ${3-selected.length} more technolog${3-selected.length===1?'y':'ies'} to unlock your 2035.</b><small>Tip: combine technologies that solve different kinds of problems.</small>`}else{out.innerHTML=`<span>SCENARIO // ${selected.join(' + ')}</span><b>${selected.map(x=>futures[x]).join(' ')}</b><small>Built from your three choices. This is a speculative scenario, not a prediction.</small>`}}
document.getElementById('resetFuture').onclick=()=>{selected=[];document.querySelectorAll('.choice').forEach(b=>b.classList.remove('selected'));document.getElementById('futureOutput').innerHTML='<span>SCENARIO // WAITING</span><b>Select 3 technologies to unlock your 2035.</b><small>Tip: combine technologies that solve different kinds of problems.</small>'};
const countEls=document.querySelectorAll('[data-count]');const countObs=new IntersectionObserver(entries=>{entries.forEach(en=>{if(en.isIntersecting&&!en.target.dataset.done){en.target.dataset.done='1';const target=+en.target.dataset.count;let v=0;const step=Math.max(1,Math.ceil(target/40));const t=setInterval(()=>{v=Math.min(target,v+step);en.target.textContent=v;if(v>=target)clearInterval(t)},30)}})});countEls.forEach(x=>countObs.observe(x));
const randomBtn=document.getElementById('randomBtn');randomBtn.onclick=()=>{showEra(Math.floor(Math.random()*eras.length));document.getElementById('timeline').scrollIntoView({behavior:'smooth'})};
const reflectionInput=document.getElementById('reflectionInput'),reflectionOutput=document.getElementById('reflectionOutput');document.getElementById('saveReflection').onclick=()=>{const v=reflectionInput.value.trim();reflectionOutput.textContent=v?`MUSEUM LABEL · “${v} changed the way I live.”`:'Type an object or idea first — the museum label is waiting.'};
let audioCtx=null;document.getElementById('soundBtn').onclick=()=>{const btn=document.getElementById('soundBtn');if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.frequency.value=62;gain.gain.value=.018;osc.connect(gain);gain.connect(audioCtx.destination);osc.start();btn.classList.add('on');btn.innerHTML='SOUND <span>ON</span>'}else if(audioCtx.state==='running'){audioCtx.suspend();btn.classList.remove('on');btn.innerHTML='SOUND <span>OFF</span>'}else{audioCtx.resume();btn.classList.add('on');btn.innerHTML='SOUND <span>ON</span>'}};
